package com.SIMRacingApps.SIMPlugins.AC.IODrivers.jnaerator;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
/**
 * JNA Wrapper for library <b>AcSharedMem</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface AcSharedMemLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "AcSharedMem";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(AcSharedMemLibrary.JNA_LIBRARY_NAME);
	public static final AcSharedMemLibrary INSTANCE = (AcSharedMemLibrary)Native.loadLibrary(AcSharedMemLibrary.JNA_LIBRARY_NAME, AcSharedMemLibrary.class);
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_OFF = (int)0;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_REPLAY = (int)1;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_LIVE = (int)2;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_PAUSE = (int)3;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_UNKNOWN = (int)-1;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_PRACTICE = (int)0;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_QUALIFY = (int)1;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_RACE = (int)2;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_HOTLAP = (int)3;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_TIME_ATTACK = (int)4;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_DRIFT = (int)5;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_DRAG = (int)6;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_NO_FLAG = (int)0;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_BLUE_FLAG = (int)1;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_YELLOW_FLAG = (int)2;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_BLACK_FLAG = (int)3;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_WHITE_FLAG = (int)4;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_CHECKERED_FLAG = (int)5;
	/** <i>native declaration : SharedFileOut.h</i> */
	public static final int AC_PENALTY_FLAG = (int)6;
}
