package com.SIMRacingApps.SIMPlugins.AC.IODrivers.jnaerator;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : SharedFileOut.h:130</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SPageFileStatic extends Structure {
  /**
   * C type : wchar_t[15]
   */
  public volatile char[] smVersion = new char[15];
  /**
   * C type : wchar_t[15]
   */
  public volatile char[] acVersion = new char[15];
  public volatile int numberOfSessions;
  public volatile int numCars;
  /**
   * C type : wchar_t[33]
   */
  public volatile char[] carModel = new char[33];
  /**
   * C type : wchar_t[33]
   */
  public volatile char[] track = new char[33];
  /**
   * C type : wchar_t[33]
   */
  public volatile char[] playerName = new char[33];
  /**
   * C type : wchar_t[33]
   */
  public volatile char[] playerSurname = new char[33];
  /**
   * C type : wchar_t[33]
   */
  public volatile char[] playerNick = new char[33];
  public volatile int sectorCount;
  public volatile float maxTorque;
  public volatile float maxPower;
  public volatile int maxRpm;
  public volatile float maxFuel;
  /**
   * C type : float[4]
   */
  public volatile float[] suspensionMaxTravel = new float[4];
  /**
   * C type : float[4]
   */
  public volatile float[] tyreRadius = new float[4];
  public volatile float maxTurboBoost;
  public volatile float deprecated_1;
  public volatile float deprecated_2;
  public volatile int penaltiesEnabled;
  public volatile float aidFuelRate;
  public volatile float aidTireRate;
  public volatile float aidMechanicalDamage;
  public volatile int aidAllowTyreBlankets;
  public volatile float aidStability;
  public volatile int aidAutoClutch;
  public volatile int aidAutoBlip;
  public volatile int hasDRS;
  public volatile int hasERS;
  public volatile int hasKERS;
  public volatile float kersMaxJ;
  public volatile int engineBrakeSettingsCount;
  public volatile int ersPowerControllerCount;
  public volatile float trackSPlineLength;
  /**
   * C type : wchar_t[33]
   */
  public volatile char[] trackConfiguration = new char[33];
  public volatile float ersMaxJ;

  public SPageFileStatic() {
    super();
  }

  protected List<String> getFieldOrder() {
    return Arrays
        .asList("smVersion", "acVersion", "numberOfSessions", "numCars", "carModel", "track",
            "playerName", "playerSurname", "playerNick", "sectorCount", "maxTorque", "maxPower",
            "maxRpm", "maxFuel", "suspensionMaxTravel", "tyreRadius", "maxTurboBoost",
            "deprecated_1", "deprecated_2", "penaltiesEnabled", "aidFuelRate", "aidTireRate",
            "aidMechanicalDamage", "aidAllowTyreBlankets", "aidStability", "aidAutoClutch",
            "aidAutoBlip", "hasDRS", "hasERS", "hasKERS", "kersMaxJ", "engineBrakeSettingsCount",
            "ersPowerControllerCount", "trackSPlineLength", "trackConfiguration", "ersMaxJ");
  }

  public SPageFileStatic(Pointer peer) {
    super(peer);
  }

  public static class ByReference extends SPageFileStatic implements Structure.ByReference {

  }

  ;

  public static class ByValue extends SPageFileStatic implements Structure.ByValue {

  }

  ;
}
